#-----------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------

# Parameters Documentation

## User-Specific Measurements
# USER_FACE_WIDTH: The horizontal distance between the outer edges of the user's cheekbones in millimeters.
# This measurement is used to scale the 3D model points for head pose estimation.
# Measure your face width and adjust the value accordingly.
USER_FACE_WIDTH: 140  # [mm]
## Camera Parameters (not currently used in calculations)
# NOSE_TO_CAMERA_DISTANCE: The distance from the tip of the nose to the camera lens in millimeters.
# Intended for future use where accurate physical distance measurements may be necessary.
NOSE_TO_CAMERA_DISTANCE: 600  # [mm]
## Configuration Parameters
# PRINT_DATA: Enable or disable the printing of data to the console for debugging.
PRINT_DATA: True
# DEFAULT_WEBCAM: Default camera source index. '0' usually refers to the built-in webcam.
WEBCAM: 0
# VIDEO_PATH: If provided, use the video for analysis. Default Webcam must be None if path is provided.
VIDEO_INPUT: None  #  /home/max/Videos/Bildschirmaufzeichnungen/Bildschirmaufzeichnung vom 2024-09-17, 14-40-29.webm
# SHOW_ALL_FEATURES: If True, display all facial landmarks on the video feed.
VIDEO_OUTPUT: output.avi
FLIP_VIDEO: True
SHOW_ALL_FEATURES: True
# LOG_DATA: Enable or disable logging of data to a CSV file.
LOG_DATA: True
# LOG_ALL_FEATURES: If True, log all facial landmarks to the CSV file.
LOG_ALL_FEATURES: False
# ENABLE_HEAD_POSE: Enable the head position and orientation estimator.
ENABLE_HEAD_POSE: True
## Logging Configuration
# LOG_FOLDER: Directory where log files will be stored.
LOG_FOLDER: "logs"
## Server Configuration
# SERVER_IP: IP address of the server for sending data via UDP (default is localhost).
SERVER_IP: "127.0.0.1"
# SERVER_PORT: Port number for the server to listen on.
SERVER_PORT: 7070
## Blink Detection Parameters
# SHOW_ON_SCREEN_DATA: If True, display blink count and head pose angles on the video feed.
SHOW_ON_SCREEN_DATA: True
# BLINK_THRESHOLD: Eye aspect ratio threshold below which a blink is registered.
BLINK_THRESHOLD: 0.51
# EYE_AR_CONSEC_FRAMES: Number of consecutive frames below the threshold required to confirm a blink.
EYE_AR_CONSEC_FRAMES: 2
## MediaPipe Model Confidence Parameters
# These thresholds determine how confidently the model must detect or track to consider the results valid.
MIN_DETECTION_CONFIDENCE: 0.8
MIN_TRACKING_CONFIDENCE: 0.8
## Angle Normalization Parameters
# MOVING_AVERAGE_WINDOW: The number of frames over which to calculate the moving average for smoothing angles.
MOVING_AVERAGE_WINDOW: 10
## Head Pose Estimation Landmark Indices
# These indices correspond to the specific facial landmarks used for head pose estimation.
LEFT_EYE_IRIS: [474, 475, 476, 477]
RIGHT_EYE_IRIS: [469, 470, 471, 472]
LEFT_EYE_OUTER_CORNER: [33]
LEFT_EYE_INNER_CORNER: [133]
RIGHT_EYE_OUTER_CORNER: [362]
RIGHT_EYE_INNER_CORNER: [263]
RIGHT_EYE_POINTS: [33, 160, 159, 158, 133, 153, 145, 144]
LEFT_EYE_POINTS: [362, 385, 386, 387, 263, 373, 374, 380]
NOSE_TIP_INDEX: 4
CHIN_INDEX: 152
LEFT_EYE_LEFT_CORNER_INDEX: 33
RIGHT_EYE_RIGHT_CORNER_INDEX: 263
LEFT_MOUTH_CORNER_INDEX: 61
RIGHT_MOUTH_CORNER_INDEX: 291
# Face Selected points indices for Head Pose Estimation
_indices_pose: [1, 33, 61, 199, 263, 291]
MAX_NUM_FACES: 1
